export const actionTypes = {
    DOWNLOAD_TASKS_FROM_LOCAL_STORAGE : 'DOWNLOAD_TASKS_FROM_LOCAL_STORAGE',
    ADD: 'ADD',
    SET_FOCUS_ON: "SET_FOCUS_ON",
    SET_FOCUS_OFF: "SET_FOCUS_OFF",
    UPDATE_TEXT_OF_THE_FOCUSED_TASK: 'UPDATE_TEXT_OF_THE_FOCUSED_TASK',
    UPDATE_TEXT_OF_THE_TASK: 'UPDATE_TEXT_OF_THE_TASK',
    CHECK_LOGIN: 'CHECK_LOGIN',
    LOGOUT: 'LOGOUT',
    SET_TEXT_OF_THE_FOCUSED_TASK: 'SET_TEXT_OF_THE_FOCUSED_TASK',
    GET_TASK_DONE: 'GET_TASK_DONE',
    DELETE: 'DELETE',
    UPDATE_TEXT_OF_LOGIN_FIELD: 'UPDATE_TEXT_OF_LOGIN_FIELD',
    SET_REMEMBER_ME: 'SET_REMEMBER_ME',
    CLEAR_ALL: 'CLEAR_ALL'
}
